name: "Get & Cache Dependencies"

description: "Get and cache dependencies for a Node.js project using npm"

inputs:
  caching:
    description: "cache or not"
    required: false
    default: true
    
outputs:
  cache-hit:
    description: "whether the cache was hit or not"
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: "Get code"
      uses: "actions/checkout@v3"
    - name: "Cache dependencies"
      if: "inputs.caching"
      id: "cache"
      uses: "actions/cache@v3"
      with:
        path: "node_modules"
        key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
    - name: "Install dependencies"
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: "npm ci"
      shell: "bash"